[package]
name = "llflash_desktop"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
cpal = { workspace = true }
egui = { workspace = true }
egui_extras = { version = "0.33.3", default-features = false, features = ["image"] }
egui-wgpu = { version = "0.33.3", features = ["winit"] }
image = { workspace = true, features = ["png"] }
egui-winit = "0.33.3"
fontdb = "0.23"
llflash_core = { path = "../core", features = ["audio", "clap", "mp3", "aac", "nellymoser", "default_compatibility_rules", "egui"] }
llflash_render = { path = "../render", features = ["clap"] }
llflash_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
llflash_video_software = { path = "../video/software", optional = true }
llflash_video_external = { path = "../video/external", features = ["openh264"], optional = true }
llflash_frontend_utils = { path = "../frontend-utils", features = ["cpal", "fs", "navigator"] }
llflash_rtmp = { path = "../rtmp" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = "0.2.5"
winit = "0.30.13"
webbrowser = "1.1.0"
url = { workspace = true }
dirs = "6.0"
rfd = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
os_info = { version = "3", default-features = false }
unic-langid = "0.9.6"
sys-locale = "0.3.2"
wgpu = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
fluent-templates = { workspace = true }
toml_edit = { workspace = true, features = ["parse"] }
gilrs = "0.11"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs"] }

tracing-tracy = { version = "0.11.3", optional = true, features = ["demangle"] }
rand = "0.9.1"
thiserror.workspace = true
async-channel.workspace = true
unicode-bidi = "0.3.18"
fontconfig = { version = "0.10.2", optional = true, features = ["dlopen"]}
memmap2.workspace = true
walkdir.workspace = true
async-task = "4.7.1"

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = "0.12.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Console", "Win32_Storage_FileSystem"] }

[build-dependencies]
vergen = { version = "9.1.0", features = ["build", "cargo"] }
vergen-gitcl = { version = "9.1.0" }
winresource = "0.1"

[package.metadata.winresource]
# https://learn.microsoft.com/en-us/windows/win32/menurc/stringfileinfo-block
ProductName = "Long Live Flash"
FileDescription = "Adobe Flash Player emulator"
CompanyName = "Long Live Flash"
LegalCopyright = "Copyright © 2018 Llflash LLC and Llflash contributors"
# InternalName should be the same as the module name
InternalName = "llflash_desktop"
OriginalFilename = "llflash.exe"

[features]
default = ["software_video", "external_video", "lzma", "fontconfig"]
jpegxr = ["llflash_core/jpegxr"]

# core features
avm_debug = ["llflash_core/avm_debug"]
lzma = ["llflash_core/lzma"]
software_video = ["llflash_video_software"]
external_video = ["llflash_video_external"]
tracy = ["tracing-tracy", "llflash_render_wgpu/profile-with-tracy"]
fontconfig = ["dep:fontconfig"]

# wgpu features
render_debug_labels = ["llflash_render_wgpu/render_debug_labels"]

# sandboxing
sandbox = []
